
import os
from PIL import Image

def crop_grid(image_path, output_dir):
    try:
        img = Image.open(image_path)
        
        # Resize logic from previous script
        original_size = img.size
        # The grid is 3x3. We assume it's square.
        # If generated by Gemini, usually 1024x1024 or similar.
        # Let's resize to standard 1023x1023 divisible by 3 (341x341)
        target_size = (1023, 1023)
        img = img.resize(target_size, Image.Resampling.LANCZOS)
        
        piece_width = target_size[0] // 3
        piece_height = target_size[1] // 3
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        count = 1
        for i in range(3): # Rows
            for j in range(3): # Cols
                left = j * piece_width
                upper = i * piece_height
                right = left + piece_width
                lower = upper + piece_height
                
                box = (left, upper, right, lower)
                piece = img.crop(box)
                
                output_path = os.path.join(output_dir, f"{count}.png")
                # Force overwrite
                piece.save(output_path)
                print(f"  Saved piece {count} to {output_path}")
                count += 1
                
    except Exception as e:
        print(f"Error processing {image_path}: {e}")

# Target just Batch 7
grid_file = "assets/uplevel-icons/source-grids/uplevel_meta_grid_9x9_v7_city_winners_final_1766058385610.png"
output_folder = "assets/uplevel-icons/source-grids/uplevel_meta_grid_9x9_v7_city_winners_final_1766058385610_pieces"

# Absolute path prefix
base_path = "/Users/chawanutcharoenthammachoke/Documents/Cursor/up-level-leaderboard/local-tournament-manager/public/"

full_grid_path = os.path.join(base_path, grid_file)
full_output_folder = os.path.join(base_path, output_folder)

print(f"Re-cropping {full_grid_path}...")
crop_grid(full_grid_path, full_output_folder)
print("Done re-cropping Batch 7.")
